---
# Areas
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - ".config/**/*"
          - ".pre-commit-config.yaml"
          - ".gitattributes"
          - ".gitignore"
area/app:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**/*"
area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**/*"
          - ".dockerignore"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - "k8s/**/*"
area/terraform:
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/**/*"
