---
name: httpenv

services:
  httpenv:
    init: true
    container_name: httpenv
    image: ghcr.io/irishlab-io/httpenv:stable-20240714-17bcc02
    pull_policy: always
    env_file: .env
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "8888:8888"
