---
name: Continous Integration - Feat/* branches

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - feat/*
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  python-poetry:
    name: Python - Poetry
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: "./app/"

    strategy:
      max-parallel: 16
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.4"
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install --verbose --no-interaction --no-root

      - name: Install project
        run: |
          poetry install --verbose --no-interaction

      - name: Run tests and generate coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m
